# Generated by Django 4.2 on 2025-10-18 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Curso')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'role': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_courses', to=settings.AUTH_USER_MODEL, verbose_name='Docente Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Materia')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('courses', models.ManyToManyField(related_name='subjects', to='academic_app.curso', verbose_name='Cursos donde se imparte')),
                ('teachers', models.ManyToManyField(limit_choices_to={'role': 'docente'}, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Docentes que la imparten')),
            ],
        ),
    ]
