# Generated by Django 4.2 on 2025-10-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='description',
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.TextField(blank=True, null=True, verbose_name='nivel académico (ej. Primaria, Secundaria, Preparatoria)'),
        ),
    ]
