# Generated by Django 4.2 on 2025-11-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0002_remove_curso_description_curso_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='nivel',
            new_name='description',
        ),
    ]
