# Generated by Django 4.2 on 2025-10-22 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_app', '0002_remove_curso_description_curso_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valor de la Calificación')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('docente', models.ForeignKey(limit_choices_to={'role': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Docente que asignó')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academic_app.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
