# Generated by Django 4.2 on 2025-07-09 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Archivo')),
                ('document_type', models.CharField(choices=[('justificativo', 'Justificativo'), ('permiso', 'Permiso'), ('formulario', 'Formulario'), ('informe', 'Informe'), ('plan_estudio', 'Plan de Estudio'), ('otro', 'Otro')], default='otro', max_length=50, verbose_name='Tipo de Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
